apiVersion: v1
kind: Secret
metadata:
  name: burrito-postgres
type: Opaque
stringData:
  password: {{ required "postgres.password is required (--set postgres.password=...)" .Values.postgres.password | quote }}
